### ISSUE TITLE
Incorrect date, off by one

### ISSUE THREAD

**Issue by cpinto** [rossta/montrose#128]
We are calculating recurring tasks based on Montrose. One of these tasks first ran on 31 December 2018 and it's meant to repeat quarterly: `pp Montrose.monthly(interval: 3, starts: '2018-12-31').events.take(5)`

The above code prints the following:

```
[Mon, 31 Dec 2018 00:00:00 UTC +00:00,
 Sun, 31 Mar 2019 00:00:00 UTC +00:00,
 Sun, 30 Jun 2019 00:00:00 UTC +00:00,
 Mon, 30 Sep 2019 00:00:00 UTC +00:00,
 Mon, 30 Dec 2019 00:00:00 UTC +00:00]
```

We'd expect the last date to be 31 December 2019, not 30 December 2019.

**Comment by rossta** [comment]
I'm sorry this behavior it not what you expect. Months are tricky because they don't all have the same number of days. For this reason, you need to be explicit when you expect a monthly recurrence on a specific day of the month. Omitting the `mday` suggests you're okay with ambiguity.

Montrose provides the `:mday` option to go with the monthly frequency. For the last day of the month, you would use `mday: 1`. For every three months starting on Dec 21, 2018, the recurrence would look like this:

```ruby
recurrence = Montrose.monthly(interval: 3, starts: '2018-12-31', mday: [-1])

recurrence.take(5)
# => [2018-12-31 00:00:00 -0500, 2019-03-31 00:00:00 -0400, 2019-06-30 00:00:00 -0400, 2019-09-30 00:00:00 -0400, 2019-12-31 00:00:00 -0500]
```
I hope that will work for your needs.

For more info on the reason for this behavior, the gem internally uses ActiveSupport's [`Time#advance`](https://www.rubydoc.info/gems/activesupport/Time:advance).

In a simplified view of how the iteration works, we take the starting time and advance it every 3 months like so:

```ruby
time = TIme.parse('2018-12-31')
5.times do
  puts time
  time = time.advance(months: 3)
end
```
The 4th iteration produces Sept 30, and `#advance` with 3 months from then will produce Dec 30.

This is somewhat different that always advancing from the start time:
```ruby
time = TIme.parse('2018-12-31')
5.times do |n|
  puts time.advance(months: 3 * n)
end
```
This strategy produces the results you were anticipating, but it's not currently how monthly iteration works though I'm always open to patches.
