### ISSUE TITLE
Refinement array_conact

### ISSUE THREAD

**Issue by damireh** [rossta/montrose#36]
Array already has a `concat` method, so Im curious about the use of the refinement to define `array_concat`?

http://ruby-doc.org/core-2.2.0/Array.html#method-i-concat

```ruby
Array(months).concat(extras) 
#vs 
months.array_concat(extras)
```

**Comment by rossta** [comment]
Yep, you're right. I'm using the refinement on `Object` since first argument to many of the methods in `Chainable` can one of several types which `array_concat` will first cast to an `Array`. So, in your example, `months` could be a `Symbol`, `String`, `Fixnum`, `Range`, `NilClass`, etc. Hence, expressions like the following would be equivalent:

```ruby
Montrose.day(:monday, :tuesday, :wednesday)
Montrose.day([:monday, :tuesday, :wednesday])
Montrose.day(1, 2, 3)
Montrose.day([1, 2, 3])
Montrose.day(1..3)
```

Does that answer your question?

**Comment by damireh** [comment]
Yes it does, thank you
